language: generic
git:
  depth: 1
#addons:
#  apt:
#    update: false
#    sources:
#    - ubuntu-toolchain-r-test
#    packages:
#      - gcc
#      - coreutils
#      - diffutils
#    - binutils
#    - gcc-6
#    - colordiff
env:
  - CC=gcc

stages:
- simple
- full

jobs:
  include:
    - stage: simple
      os: linux
      name: "Some GNU/Linux"
      script:
      - '$CC --version'
      - .scripts/travis/test_all.sh
    - stage: full
      os: osx
      name: "Simple macOS"
      install:
      - .scripts/travis/install.sh
      script:
      - '$CC --version'
      - .scripts/travis/test_all.sh
        #    - stage: full
        #      install:
        #      - .scripts/travis/install.sh
        #      script:
        #      - '$CC --version'
        #      - .scripts/travis/test_all.sh
        #      os: linux
        #      dist: xenial
        #      sudo: required
        #      name: "Xenial /GCC 8.1/ sanitized & with Intel MPX"
        #      env: CC=gcc-8 TEST_SANITIZE_MODE=gcc-8-mpx
        #      addons:
        #        apt:
        #          update: true

    - stage: full
      install:
      - .scripts/travis/install.sh
      script:
      - '$CC --version'
      - .scripts/travis/test_all.sh
      os: linux
      dist: xenial
      name: "Xenial GCC 8 sanitized"
      env: CC=gcc-8
      addons:
        apt:
          update: true
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-8
          - binutils



